export const CHESS_FACTS = [
  'A chessboard has 64 squares arranged in eight ranks and eight files.',
  'Each player begins with 16 pieces: one king, one queen, two rooks, two bishops, two knights and eight pawns.',
  'White always makes the first move, after which the players alternate.',
  'The square nearest each player on the right must be a light square.',
  'Ranks run horizontally; files run vertically; diagonals contain squares of one colour.',
  'A bishop moves diagonally and therefore stays on the same colour complex for the whole game.',
  'A rook moves along ranks and files.',
  'A queen combines the rook’s rank-and-file movement with the bishop’s diagonal movement.',
  'A knight moves to a nearby square that is not on the same rank, file or diagonal.',
  'Bishops, rooks and queens cannot jump over intervening pieces.',
  'A pawn may advance two squares only on its first move, and only if both squares are clear.',
  'Pawns move straight ahead but normally capture one square diagonally forward.',
  'An en-passant capture is legal only on the move immediately after the opposing pawn advances two squares.',
  'A promoting pawn may become a queen, rook, bishop or knight of the same colour.',
  'Promotion is not limited by which pieces have already been captured.',
  'A promoted piece takes effect immediately on the promotion square.',
  'Castling counts as one move of the king even though a rook moves too.',
  'In standard chess, the king moves two squares toward the rook when castling.',
  'A king that has moved permanently loses its right to castle.',
  'A rook that has moved can no longer be used for castling.',
  'Castling is blocked while the king is in check, crosses an attacked square or lands on one.',
  'No piece may make a move that leaves its own king in check.',
  'Checkmate ends the game immediately; the king itself is never captured.',
  'Stalemate is a draw: the player to move has no legal move but is not in check.',
  'A dead position is drawn when no possible legal sequence can produce checkmate.',
  'A correctly claimed third occurrence of the same position can end the game as a draw.',
  'For repetition, castling and en-passant rights are part of what makes two positions the same.',
  'A player may claim a draw after 50 moves by each side without a pawn move or capture.',
  'Five occurrences of the same position produce an automatic draw under FIDE rules.',
  'Seventy-five moves by each side without a pawn move or capture produce an automatic draw unless the last move is checkmate.',
  'A win normally scores one point, a draw half a point and a loss zero.',
  'In over-the-board competition, each move must be played with one hand only.',
  'A player may say “j’adoube” or “I adjust” before straightening a piece on its square.',
  'The touch-move rule normally requires a deliberately touched movable piece to be moved.',
  'A player must press the chess clock with the same hand used to make the move.',
  'FIDE defines blitz as ten minutes or less per player, including the time-control increment calculation.',
  'FIDE defines rapid chess as more than ten but less than sixty minutes per player under its time calculation.',
  'FIDE recognises algebraic notation for its tournaments and matches.',
  'In algebraic notation, pawns are written without a piece letter: e4 rather than Pe4.',
  'Every square has a unique letter-and-number name, from a1 to h8.',
  'FIDE was founded in Paris in 1924.',
  'FIDE’s motto “Gens una Sumus” means “We are one Family.”',
  'The first official Chess Olympiad was organised in 1927.',
  'FIDE began overseeing the World Chess Championship in 1948.',
  'The first FIDE Grandmaster titles were awarded in 1950.',
  'The first official FIDE rating list appeared in 1971.',
  'Claude Shannon’s 1950 computer-chess paper estimated a game tree around 10¹²⁰ possibilities.',
] as const;

export function pickChessFact(random: () => number = Math.random): string {
  const sample = Math.min(Math.max(random(), 0), 0.999999999999);
  return CHESS_FACTS[Math.floor(sample * CHESS_FACTS.length)] ?? CHESS_FACTS[0];
}
