import type { RepertoireSide } from '../domain/repertoire.js';

const KNOWN_COURSE_SIDES: Readonly<Record<string, Exclude<RepertoireSide, 'unresolved'>>> = {
  '1-e4-part-2-sicilian': 'white',
  '1-e4-part-3-caro-etc': 'white',
  'aggressive-italian-game': 'white',
  'aggressive-ruy-lopez': 'white',
  'alekhine-s-defense': 'black',
  'anti-sicilian-for-white': 'white',
  'anti-sicilians-for-black': 'black',
  'caro-kann': 'black',
  'caro-kann-bonus-lines': 'black',
  'd4-sidelines-for-black': 'black',
  'dutch-defense-sidelines': 'black',
  'four-knights-sicilian': 'black',
  'italian-center-attack': 'white',
  'king-s-knight-opening': 'white',
  'kings-indian-defense': 'black',
  'larsen-s-opening-1-b3': 'white',
  'london-system': 'white',
  'owen-s-defense-e6-b6': 'black',
  'queen-s-gambit-accepted': 'black',
  'queen-s-gambit-declined': 'black',
  'scandinavian-defense': 'black',
  'sicilian-dragon': 'black',
  'stonewall-dutch': 'black',
  'the-alapin-sicilian': 'white',
  'the-albin-countergambit': 'black',
  'the-b3-french': 'white',
  'the-b3-sicilian': 'white',
  'the-beefeater-defense': 'black',
  'the-bird-opening': 'white',
  'the-budapest-gambit': 'black',
  'the-czech-benoni': 'black',
  'the-danish-gambit': 'white',
  'the-dark-vienna': 'white',
  'the-english-opening': 'white',
  'the-englund-gambit': 'black',
  'the-fried-liver-attack': 'white',
  'the-gotham-dutch': 'black',
  'the-gotham-gambit': 'black',
  'the-grunfeld-defense': 'black',
  'the-hillbilly-attack': 'white',
  'the-jaenisch-gambit': 'black',
  'the-leningrad-dutch': 'black',
  'the-modern-defense': 'black',
  'the-ponziani': 'white',
  'the-portuguese-gambit': 'black',
  'the-scotch-game': 'white',
  'the-smith-morra-gambit': 'white',
  'the-trompowsky-attack': 'white',
  'traxler-counterattack': 'black',
  'vienna-game': 'white',
};

export function knownCourseSide(
  courseFolder: string,
): Exclude<RepertoireSide, 'unresolved'> | undefined {
  return KNOWN_COURSE_SIDES[courseFolder];
}
